site_name: Christmas Dream
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: teal

  logo: assets/images/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
extra_css:
  - assets/stylesheets/extra.css

